[package]
name = "djb2macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "djb2macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
djb2 = { path = "../djb2" }
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.68", features = ["extra-traits"] }
